version: 2

tox: &tox
  working_directory: ~/repo
  steps:
    - checkout
    - run:
        name: install tox
        command: pip install --user tox
    - run:
        name: run tox
        command: ~/.local/bin/tox -r

jobs:
  python27-unit:
    <<: *tox
    docker:
      - image: circleci/python:2.7
    environment:
      TOXENV: py27-unit
  python36-unit:
    <<: *tox
    docker:
      - image: circleci/python:3.6
    environment:
      TOXENV: py36-unit
  python37-unit:
    <<: *tox
    docker:
      - image: circleci/python:3.7
    environment:
      TOXENV: py37-unit
  python27-e2e:
    <<: *tox
    docker:
      - image: circleci/python:2.7
    environment:
      TOXENV: py27-e2e
  python36-e2e:
    <<: *tox
    docker:
      - image: circleci/python:3.6
    environment:
      TOXENV: py36-e2e
  python37-e2e:
    <<: *tox
    docker:
      - image: circleci/python:3.7
    environment:
      TOXENV: py37-e2e
workflows:
  version: 2
  test:
    jobs:
      - python27-unit
      - python36-unit
      - python37-unit
      - python27-e2e
      - python36-e2e
      - python37-e2e
