version: 2
jobs:
  dependencies:
    docker:
      - image: circleci/python:3.6.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - pip-packages-v2-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - pip-packages-v2-{{ .Branch }}-
            - pip-packages-v2-
      - run: pipenv install . --dev
      - save_cache:
          paths:
            - ~/.local/share/virtualenvs/venv  # this path depends on where pipenv creates a virtualenv
          key: pip-packages-v2-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

  unit-test:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - pip-packages-v2-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - pip-packages-v2-{{ .Branch }}-
            - pip-packages-v2-
      - run: pipenv run nosetests tests/*
            
            
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - dependencies
      - unit-test:
          requires:
            - dependencies