version: 2
jobs:
  checkout:
    working_directory: ~/repo
    docker:
      - image: alpine/git:latest
    steps:
      - persist_to_workspace:
          root: ~/
          paths:
            - ./repo

  unit-test:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.4
    steps:
      - attach_workspace:
          at: ~/
      - run:
          command: |
            sudo pip install pipenv
            pipenv install .
            pipenv install nose
      - run: nosetests tests/*
            
            
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - checkout
      - unit-test:
          requires:
            - checkout
