version: 2
jobs:
  checkout:
    working_directory: ~/repo
    docker:
      - image: alpine/git:latest
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/
          paths:
            - ./repo

  dependencies:
    docker:
      - image: circleci/python:3.6.4
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install .
            pipenv install nose
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"

  unit-test:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.4
    steps:
      - attach_workspace:
          at: ~/
      - run: sudo apt install python-nose
      - run: nosetests tests/*
            
            
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - checkout
      - dependencies:
          requires:
            - checkout
      - unit-test:
          requires:
            - dependencies