version: 2
jobs:
  dependencies-python-2:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - pip2-packages-v3-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - pip2-packages-v3-{{ .Branch }}-
            - pip2-packages-v3-
      - run: pipenv install . --dev
      - save_cache:
          paths:
            - ~/.local/share/virtualenvs  # this path depends on where pipenv creates a virtualenv
          key: pip2-packages-v3-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run: pipenv run pip list

  test-python-2:
    working_directory: ~/repo
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - pip2-packages-v3-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - pip2-packages-v3-{{ .Branch }}-
            - pip2-packages-v3-
      - run: pipenv run nosetests tests/*

  dependencies-python-3:
    docker:
      - image: circleci/python:3.6.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - pip-packages-v3-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - pip-packages-v3-{{ .Branch }}-
            - pip-packages-v3-
      - run: pipenv install . --dev
      - save_cache:
          paths:
            - ~/.local/share/virtualenvs  # this path depends on where pipenv creates a virtualenv
          key: pip-packages-v3-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run: pipenv run pip list

  test-python-3:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - pip-packages-v3-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - pip-packages-v3-{{ .Branch }}-
            - pip-packages-v3-
      - run: pipenv run nosetests tests/*
            
            
workflows:
  version: 2
  build-test:
    jobs:
      - dependencies-python-2
      - dependencies-python-3
      - test-python-2:
          requires:
            - dependencies-python-2
      - test-python-3:
          requires:
            - dependencies-python-3